修复缺少 libssl1.1

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -49,7 +49,8 @@ env:
   # COMMIT: 528
 
   # github.repository as <account>/<repo>
-
+  NED_LIBFIX_VERSIONS_B_S_rC: "v2_2.3.0,v2s_2.1.0_r111"
+  TEST_PLATFORM: "linux/386"
 jobs:
   init-version:
     runs-on: ubuntu-latest
@@ -97,13 +98,14 @@ jobs:
               LOG_WARNING USE env.BIG_VERSION
               BUILD_BIG_VERSION=${{ env.BIG_VERSION }}
             fi
-            BUILD_PLATFORMS='linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7'
+            BUILD_PLATFORMS='linux/amd64,linux/386,linux/v8,linux/arm/v7'
             echo BBUILD_IG_VERSION: ${BUILD_BIG_VERSION}
             echo "BUILD_BIG_VERSION=${BUILD_BIG_VERSION}" >> $GITHUB_OUTPUT
             echo "BUILD_VERSION_B_S_rC=${BUILD_BIG_VERSION}" >> $GITHUB_OUTPUT
             echo "BUILD_PLATFORMS=${BUILD_PLATFORMS}" >> $GITHUB_OUTPUT
+            # Error: buildx failed with: ERROR: docker exporter does not currently support exporting manifest lists
             # echo "TEST_PLATFORM=${BUILD_PLATFORMS}" >> $GITHUB_OUTPUT
-            echo "TEST_PLATFORM=linux/386" >> $GITHUB_OUTPUT
+            echo "TEST_PLATFORM=${{ env.TEST_PLATFORM }}" >> $GITHUB_OUTPUT
             exit 0
           fi
           PROJECT_ROOT_DIR=$(pwd)
@@ -145,8 +147,8 @@ jobs:
           echo "BUILD_COMMIT=${BUILD_COMMIT}" >> $GITHUB_OUTPUT
           echo "BUILD_PLATFORMS=${BUILD_PLATFORMS}" >> $GITHUB_OUTPUT
           # echo "TEST_PLATFORM=${BUILD_PLATFORMS}" >> $GITHUB_OUTPUT
-          if [[ ${BUILD_PLATFORMS} =~ 386 ]];then
-            echo "TEST_PLATFORM=linux/386" >> $GITHUB_OUTPUT
+          if [[ ${BUILD_PLATFORMS} =~ ${{ env.TEST_PLATFORM }} ]];then
+            echo "TEST_PLATFORM=${{ env.TEST_PLATFORM }}" >> $GITHUB_OUTPUT
           else
             echo "TEST_PLATFORM=${BUILD_PLATFORMS%%,*}" >> $GITHUB_OUTPUT
           fi
@@ -271,7 +273,7 @@ jobs:
             type=raw,value=releases-v1,enable=${{ needs.init-version.outputs.BUILD_BIG_VERSION == 'v1' && needs.init-version.outputs.BUILD_SMALL_VERSION == '' && needs.init-version.outputs.BUILD_COMMIT == '' }}
             type=raw,value=${{ format( '{0}_{1}_r{2}', needs.init-version.outputs.BUILD_BIG_VERSION, needs.init-version.outputs.BUILD_SMALL_VERSION, needs.init-version.outputs.BUILD_COMMIT ) }}, enable=${{ needs.init-version.outputs.BUILD_BIG_VERSION != '' && needs.init-version.outputs.BUILD_SMALL_VERSION != '' && needs.init-version.outputs.BUILD_COMMIT != '' }}
             type=raw,value=${{ format( '{0}_{1}', needs.init-version.outputs.BUILD_BIG_VERSION, needs.init-version.outputs.BUILD_SMALL_VERSION, needs.init-version.outputs.BUILD_COMMIT ) }}, enable=${{ needs.init-version.outputs.BUILD_BIG_VERSION != '' && needs.init-version.outputs.BUILD_SMALL_VERSION != '' && needs.init-version.outputs.BUILD_COMMIT == '' }}
-            type=raw,value=${{ format( 'v.{1}_r{2}',  needs.init-version.outputs.BUILD_BIG_VERSION, needs.init-version.outputs.BUILD_SMALL_VERSION, needs.init-version.outputs.BUILD_COMMIT ) }}, enable=${{ needs.init-version.outputs.BUILD_SMALL_VERSION != '' && needs.init-version.outputs.BUILD_COMMIT != '' }}
+            type=raw,value=${{ format( 'v.{1}_r{2}', needs.init-version.outputs.BUILD_BIG_VERSION, needs.init-version.outputs.BUILD_SMALL_VERSION, needs.init-version.outputs.BUILD_COMMIT ) }}, enable=${{ needs.init-version.outputs.BUILD_SMALL_VERSION != '' && needs.init-version.outputs.BUILD_COMMIT != '' }}
             type=raw,value=${{ format( 'v.{1}',  needs.init-version.outputs.BUILD_BIG_VERSION, needs.init-version.outputs.BUILD_SMALL_VERSION, needs.init-version.outputs.BUILD_COMMIT ) }}, enable=${{ needs.init-version.outputs.BUILD_SMALL_VERSION != '' }}
             type=raw,value=${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
           labels: |
@@ -306,6 +308,16 @@ jobs:
               echo -e "\033[0;31m[ERROR] $* \033[0m"
           }
           set -e
+          ned_libfix_versions_b_s_rc=${{ env.NED_LIBFIX_VERSIONS_B_S_rC }}
+          l_ned_libfix_versions_b_s_rc=(${ned_libfix_versions_b_s_rc//,/ })
+          for ned_libfix_versions_b_s_rc in ${l_platforms[@]};do
+            if [[ "${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}" == "${ned_libfix_versions_b_s_rc}" ]];then
+              LOG_WARNING 需要修复 - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
+              LOG_WARNING 使用 Dockerfile.ubuntu-18.04 - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
+              echo 'build_dockerfile=Dockerfile.ubuntu-18.04'>> $GITHUB_OUTPUT
+              exit 0
+            fi
+          done
           LOG_WARNING "Test start: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
           platforms=${{ needs.init-version.outputs.TEST_PLATFORM }}
           l_platforms=(${platforms//,/ })
@@ -317,7 +329,7 @@ jobs:
               edge -h 2>&1 | xargs -I {} echo {})"
             if [[ -n "$(echo ${edge_result} | grep -E '(libcrypto.so.1.0.0)|(/lib/ld-linux.so.3)')" ]];then
               LOG_ERROR 出错了: ${edge_result}
-              LOG_WARNING 使用 Dockerfile.ubuntu-18.04
+              LOG_WARNING 使用 Dockerfile.ubuntu-18.04 - ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}
               echo 'build_dockerfile=Dockerfile.ubuntu-18.04'>> $GITHUB_OUTPUT
               exit 0
             fi
@@ -380,10 +392,20 @@ jobs:
           }
           set -e
           LOG_WARNING "Test start: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
+          flag_test_pass="true"
           platforms=${{ needs.init-version.outputs.BUILD_PLATFORMS }}
           l_platforms=(${platforms//,/ })
           for test_platform in ${l_platforms[@]};do
             LOG_WARNING "Test for platform: ${test_platform}"
+            edge_result="$(docker run --rm \
+              --platform ${test_platform} \
+              ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
+              edge -h 2>&1 | xargs -I {} echo {})"
+            if [[ -z "$(echo ${edge_result,,} | grep welcome)" ]];then
+              LOG_ERROR 出错了: ${test_platform} - ${edge_result}
+              flag_test_pass="false"
+              continue
+            fi
             docker run --rm \
               --platform ${test_platform} \
               ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }} \
@@ -404,6 +426,10 @@ jobs:
               supernode -h  || echo 
             # LOG_WARNING "Test done - supernode"
           done
+          if [[ "${flag_test_pass}" != "true" ]];then
+            LOG_ERROR "Test faild: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
+            exit 1
+          fi
           LOG_WARNING "Test done: ${{ needs.init-version.outputs.BUILD_VERSION_B_S_rC }}"
           echo 'build_dockerfile=Dockerfile'>> $GITHUB_OUTPUT
           exit 0
